config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  root 'questions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question


	validates :content, :name, presence: {message:'必須項目'}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :answer


	validates :content, :name, presence: {message:'必須項目'}
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	before_action :set_answer, only: [:show, :edit, :update, :destroy]


	def index
		redirect_to '/questions'
	end


	def show
		redirect_to '/questions'
	end


	def new
		@answer = Answer.new
	end


	def edit
		redirect_to '/questions'
	end


	def create
		end_counter = 10 # 終了にする回答数
		@answer = Answer.new(answer_params)
		respond_to do |format|
			if @answer.save
				num = Answer.where('question_id = ?',@answer.question_id).count
				if num >= end_counter then
					q = Question.find @answer.question_id
					q.finished = true
					q.save
				end
				format.html {
					redirect_to '/questions/' + @answer.question_id.to_s
				}
				format.json { render :show, status: :created, location: @answer }
			else
				format.html { render :new }
				format.json { render json: @answer.errors, status: :unprocessable_entity }
			end
		end
	end


	def update
		redirect_to '/questions'
	end


	def destroy
		redirect_to '/questions'
	end


	private
	def set_answer
		@answer = Answer.find(params[:id])
	end


	def answer_params
		params.require(:answer).permit(:question_id, :content, :name)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_action :set_question, only: [:show, :edit, :update, :destroy]
	layout 'questions'


	def index
		@questions = Question.all.order created_at: :desc
	end


	def show
		@answer = Answer.new
		@answer.question_id = params[:id]
	end


	def new
		@question = Question.new
	end


	def edit
		redirect_to '/questions'
	end


	def create
		@question = Question.new(question_params)
		respond_to do |format|
			if @question.save
				format.html { redirect_to '/questions'}
				format.json { render :show, status: :created, location: @question }
			else
				format.html { render :new }
				format.json { render json: @question.errors, status: :unprocessable_entity }
			end
		end
	end


	def update
		redirect_to '/questions'
	end


	def destroy
		redirect_to '/questions'
	end


	private
	def set_question
		@question = Question.find(params[:id])
	end


	def question_params
		params.require(:question).permit(:title, :content, :name, :finished)
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question_id %>
    <%= form.number_field :question_id %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Content</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.question_id %></td>
        <td><%= answer.content %></td>
        <td><%= answer.name %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @answer.content %>
</p>

<p>
  <strong>Name:</strong>
  <%= @answer.name %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appweb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/questions.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>appweb</title>
		<%= csrf_meta_tags %>


		<%= stylesheet_link_tag 'questions', 
			'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'questions', 
			'data-turbolinks-track': 'reload' %>
	</head>


	<body>
		<%= yield %>
	</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(question) do |f| %>
	<% if question.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>
			<ul>
			<% question.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>


	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>


	<div class="field">
		<%= f.label :content %>
		<%= f.text_area :content, cols:40, rows:10 %>
	</div>


	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>


	<%= f.hidden_field :finished, { value:false } %>


	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/questions/_form2.html.erb
<%= form_for(answer) do |f| %>
	<% if answer.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>
			<ul>
			<% answer.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<%= f.hidden_field :question_id, {value: answer.question_id} %>

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :content %>
		<%= f.text_area :content, cols:40, rows:5 %>
	</div>
	<br>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>


<h1>質問リスト</h1>


<table class="qlist">
	<thead>
		<tr>
			<th>Title</th>
			<th>Finished</th>
			<th></th>
		</tr>
	</thead>


	<tbody>
		<% @questions.each do |question| %>
			<tr>
				<td><%= question.title %></td>
				<td><%= question.finished ? '終了' : '受付中' %></td>
				<td><%= link_to 'Show', question %></td>
				
			</tr>
		<% end %>
	</tbody>
</table>


<br>


<%= link_to '※新たに質問する', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>


<h1>質問と回答</h1>


<div class="question">
	<h2 class="title">
		<%= @question.title %>
	</h2>
	<p class="content">
		<%= @question.content %>
	</p>
	<p class="q_name">
		<%= @question.name %>
	</p>
	<span class="<%= @question.finished ? 'finished' : 'not_finished' %>">
		<%= @question.finished ? '終了' : '受付中' %>
	</span>
</div>


<% if @question.finished? == false then %>
	<div class="answer_form">
		<h2>※回答する</h2>
		<%= render 'form2', answer: @answer %>
	</div>
<% end %>


<h2>※これまで寄せられた回答</h2>


<% if @question.answer.count == 0 then %>
	<p class="answer">※まだありません。</p>
<% else %>
	<% @question.answer.reverse_each do |re| %>
		<p class="answer">
				<%= re.content + ' (' + re.name + ')' %>
		</p>
	<% end %>
<% end %>

<%= link_to '質問一覧に戻る', questions_path %>